-- Creatorverse: the single table backing the whole app.
--
-- "imageURL" MUST stay double-quoted. Postgres folds unquoted identifiers to
-- lower case, so `imageURL text` would silently create a column named
-- `imageurl`. PostgREST is case-sensitive, so the app's `creator.imageURL`
-- would then read as undefined on every row -- with no error anywhere.
-- Every later SQL statement touching this column must quote it too.

create table public.creators (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  name        text not null,
  url         text not null,
  description text,
  "imageURL"  text
);

-- Row Level Security intentionally left disabled, per the WEB103 prework spec.
-- This makes the publishable key write-capable against this table; acceptable
-- for a throwaway coursework dataset, not a pattern to carry into real work.
